#!/bin/bash
# ThemeR Studio v2.0 by CorCor67
# v2.0 TheNeXGen

# Paths
ts=~/ThemeR-Studio_V2
s=$ts/scripts
tools=$ts/.tools
ws=$ts/Android

# Install Programs
$s/installubuntu.sh

# Setup Directories
$s/workspace.sh

# Setup SDK
$s/sdkdl.sh

# Have user manually edit in path for SDK
$s/tellBash.sh

# Launch Android script from SDK so user can install platforms and tools.
$s/launchandroid.sh

echo ""
echo "Done! Thank you for using ThemeR-Studio, press enter to close."
read this
